set_location_assignment PIN_F16 -to RST_N

set_location_assignment PIN_P3 -to FLASH_ADDR[21]
set_location_assignment PIN_P1 -to FLASH_ADDR[20]
set_location_assignment PIN_M6 -to FLASH_ADDR[19]
set_location_assignment PIN_M5 -to FLASH_ADDR[18]
set_location_assignment PIN_R5 -to FLASH_ADDR[17]
set_location_assignment PIN_L6 -to FLASH_ADDR[16]
set_location_assignment PIN_L7 -to FLASH_ADDR[15]
set_location_assignment PIN_M1 -to FLASH_ADDR[14]
set_location_assignment PIN_M2 -to FLASH_ADDR[13]
set_location_assignment PIN_M3 -to FLASH_ADDR[12]
set_location_assignment PIN_N1 -to FLASH_ADDR[11]
set_location_assignment PIN_N2 -to FLASH_ADDR[10]
set_location_assignment PIN_P2 -to FLASH_ADDR[9]
set_location_assignment PIN_M4 -to FLASH_ADDR[8]
set_location_assignment PIN_M8 -to FLASH_ADDR[7]
set_location_assignment PIN_N6 -to FLASH_ADDR[6]
set_location_assignment PIN_N5 -to FLASH_ADDR[5]
set_location_assignment PIN_N7 -to FLASH_ADDR[4]
set_location_assignment PIN_P6 -to FLASH_ADDR[3]
set_location_assignment PIN_P5 -to FLASH_ADDR[2]
set_location_assignment PIN_P7 -to FLASH_ADDR[1]
set_location_assignment PIN_Y2 -to FLASH_ADDR[0]
set_location_assignment PIN_Y1 -to FLASH_DATA[7]
set_location_assignment PIN_W1 -to FLASH_DATA[6]
set_location_assignment PIN_J8 -to FLASH_DATA[5]
set_location_assignment PIN_V2 -to FLASH_DATA[4]
set_location_assignment PIN_U1 -to FLASH_DATA[3]
set_location_assignment PIN_H6 -to FLASH_DATA[2]
set_location_assignment PIN_J6 -to FLASH_DATA[1]
set_location_assignment PIN_R7 -to FLASH_DATA
set_location_assignment PIN_R6 -to FLASH_RD_N
set_location_assignment PIN_N8 -to FLASH_SEL_N
set_location_assignment PIN_P4 -to FLASH_WR_N
set_location_assignment PIN_T3 -to Flash_WP
set_location_assignment PIN_R1 -to Flash_RST_N
set_location_assignment PIN_AA1 -to Flash_BYTE

set_location_assignment PIN_A7 -to DRAM_ADDR[11]
set_location_assignment PIN_B4 -to DRAM_ADDR[10]
set_location_assignment PIN_B7 -to DRAM_ADDR[9]
set_location_assignment PIN_C7 -to DRAM_ADDR[8]
set_location_assignment PIN_A6 -to DRAM_ADDR[7]
set_location_assignment PIN_B6 -to DRAM_ADDR[6]
set_location_assignment PIN_C6 -to DRAM_ADDR[5]
set_location_assignment PIN_A5 -to DRAM_ADDR[4]
set_location_assignment PIN_C3 -to DRAM_ADDR[3]
set_location_assignment PIN_B3 -to DRAM_ADDR[2]
set_location_assignment PIN_A3 -to DRAM_ADDR[1]
set_location_assignment PIN_C4 -to DRAM_ADDR[0]
set_location_assignment PIN_A4 -to DRAM_BA[1]
set_location_assignment PIN_B5 -to DRAM_BA[0]
set_location_assignment PIN_G8 -to DRAM_CAS_N
set_location_assignment PIN_E6 -to DRAM_CKE
set_location_assignment PIN_G7 -to DRAM_CS_N
set_location_assignment PIN_F10 -to DRAM_DQ[15]
set_location_assignment PIN_E10 -to DRAM_DQ[14]
set_location_assignment PIN_A10 -to DRAM_DQ[13]
set_location_assignment PIN_B10 -to DRAM_DQ[12]
set_location_assignment PIN_C10 -to DRAM_DQ[11]
set_location_assignment PIN_A9 -to DRAM_DQ[10]
set_location_assignment PIN_B9 -to DRAM_DQ[9]
set_location_assignment PIN_A8 -to DRAM_DQ[8]
set_location_assignment PIN_F8 -to DRAM_DQ[7]
set_location_assignment PIN_G11 -to DRAM_DQ[6]
set_location_assignment PIN_G9 -to DRAM_DQ[5]
set_location_assignment PIN_F9 -to DRAM_DQ[4]
set_location_assignment PIN_E9 -to DRAM_DQ[3]
set_location_assignment PIN_H10 -to DRAM_DQ[2]
set_location_assignment PIN_G10 -to DRAM_DQ[1]
set_location_assignment PIN_D10 -to DRAM_DQ[0]
set_location_assignment PIN_B8 -to DRAM_DQM[1]
set_location_assignment PIN_E7 -to DRAM_DQM[0]
set_location_assignment PIN_F7 -to DRAM_RAS_N
set_location_assignment PIN_D6 -to DRAM_WE_N
set_location_assignment PIN_E5 -to DRAM_CLK

#set_location_assignment PIN_K1 -to EPCS_DQ
#set_location_assignment PIN_E2 -to EPCS_SCE
#set_location_assignment PIN_D1 -to EPCS_SDO
#set_location_assignment PIN_K2 -to EPCS_DCLK

set_location_assignment PIN_G21 -to CLK_50M
set_location_assignment PIN_A12 -to CLK_IN
set_location_assignment PIN_T16 -to CLK_OUT

set_location_assignment PIN_J18 -to KEY[0]
set_location_assignment PIN_K19 -to KEY[1]
set_location_assignment PIN_K18 -to KEY[2]
set_location_assignment PIN_K17 -to KEY[3]

set_location_assignment PIN_E16 -to SW_CODE
set_location_assignment PIN_L8 -to SW_CODE_L
set_location_assignment PIN_D19 -to SW_CODE_R
set_location_assignment PIN_K8 -to SW1
set_location_assignment PIN_F15 -to SW2

set_location_assignment PIN_H20 -to SW[0]
set_location_assignment PIN_H19 -to SW[1]

set_location_assignment PIN_AB4 -to GPIO_P6[5]
set_location_assignment PIN_AA4 -to GPIO_P6[6]
set_location_assignment PIN_Y3 -to GPIO_P6[7]
set_location_assignment PIN_Y4 -to GPIO_P6[8]
set_location_assignment PIN_V11 -to GPIO_P6[9]
set_location_assignment PIN_Y6 -to GPIO_P6[10]
set_location_assignment PIN_V9 -to GPIO_P6[11]
set_location_assignment PIN_V10 -to GPIO_P6[12]
set_location_assignment PIN_W8 -to GPIO_P6[13]
set_location_assignment PIN_Y8 -to GPIO_P6[14]
set_location_assignment PIN_AB10 -to GPIO_P6[15]
set_location_assignment PIN_AA10 -to GPIO_P6[16]
set_location_assignment PIN_Y10 -to GPIO_P6[17]
set_location_assignment PIN_W10 -to GPIO_P6[18]
set_location_assignment PIN_AB9 -to GPIO_P6[19]
set_location_assignment PIN_AA9 -to GPIO_P6[20]
set_location_assignment PIN_AB8 -to GPIO_P6[21]
set_location_assignment PIN_AA8 -to GPIO_P6[22]
set_location_assignment PIN_AB7 -to GPIO_P6[23]
set_location_assignment PIN_AA7 -to GPIO_P6[24]
set_location_assignment PIN_V8 -to GPIO_P6[25]
set_location_assignment PIN_U9 -to GPIO_P6[26]
set_location_assignment PIN_Y7 -to GPIO_P6[27]
set_location_assignment PIN_W7 -to GPIO_P6[28]
set_location_assignment PIN_AB5 -to GPIO_P6[29]
set_location_assignment PIN_AA5 -to GPIO_P6[30]
set_location_assignment PIN_V7 -to GPIO_P6[31]
set_location_assignment PIN_W6 -to GPIO_P6[32]
set_location_assignment PIN_AB3 -to GPIO_P6[33]
set_location_assignment PIN_AA3 -to GPIO_P6[34]
set_location_assignment PIN_V5 -to GPIO_P6[35]
set_location_assignment PIN_V6 -to GPIO_P6[36]

set_location_assignment PIN_P15 -to LED[3]
set_location_assignment PIN_R15 -to LED[2]
set_location_assignment PIN_N18 -to LED[1]
set_location_assignment PIN_N17 -to LED[0]

set_location_assignment PIN_AA21 -to GPIO_PB[12]
set_location_assignment PIN_R20 -to GPIO_PA[11]
set_location_assignment PIN_P17 -to GPIO_PB[11]
set_location_assignment PIN_M20 -to GPIO_PA[10]
set_location_assignment PIN_M19 -to GPIO_PB[10]
set_location_assignment PIN_M22 -to GPIO_PA[9]
set_location_assignment PIN_M21 -to GPIO_PB[9]
set_location_assignment PIN_N22 -to GPIO_PA[8]
set_location_assignment PIN_N21 -to GPIO_PB[8]
set_location_assignment PIN_N20 -to GPIO_PA[7]
set_location_assignment PIN_N19 -to GPIO_PB[7]
set_location_assignment PIN_P22 -to GPIO_PA[6]
set_location_assignment PIN_P21 -to GPIO_PB[6]
set_location_assignment PIN_R22 -to GPIO_PA[5]
set_location_assignment PIN_R21 -to GPIO_PB[5]
set_location_assignment PIN_U22 -to GPIO_PA[4]
set_location_assignment PIN_U21 -to GPIO_PB[4]
set_location_assignment PIN_V22 -to GPIO_PA[3]
set_location_assignment PIN_V21 -to GPIO_PB[3]
set_location_assignment PIN_W22 -to GPIO_PA[2]
set_location_assignment PIN_W21 -to GPIO_PB[2]
set_location_assignment PIN_U20 -to GPIO_PA[1]
set_location_assignment PIN_U19 -to GPIO_PB[1]
set_location_assignment PIN_Y22 -to GPIO_PA[0]
set_location_assignment PIN_Y21 -to GPIO_PB[0]
set_location_assignment PIN_K7 -to GPIO_PA[15]
set_location_assignment PIN_J7 -to GPIO_PB[15]
set_location_assignment PIN_M16 -to GPIO_PA[14]
set_location_assignment PIN_P20 -to GPIO_PB[14]
set_location_assignment PIN_W19 -to GPIO_PA[13]
set_location_assignment PIN_R19 -to GPIO_PB[13]
set_location_assignment PIN_W20 -to GPIO_PA[12]

set_location_assignment PIN_F20 -to LCD_DATA[15]
set_location_assignment PIN_F19 -to LCD_DATA[14]
set_location_assignment PIN_C22 -to LCD_DATA[13]
set_location_assignment PIN_C21 -to LCD_DATA[12]
set_location_assignment PIN_B22 -to LCD_DATA[11]
set_location_assignment PIN_B21 -to LCD_DATA[10]
set_location_assignment PIN_C20 -to LCD_DATA[9]
set_location_assignment PIN_D20 -to LCD_DATA[8]
set_location_assignment PIN_E12 -to LCD_DATA[7]
set_location_assignment PIN_G18 -to LCD_DATA[6]
set_location_assignment PIN_C15 -to LCD_DATA[5]
set_location_assignment PIN_E14 -to LCD_DATA[4]
set_location_assignment PIN_H15 -to LCD_DATA[3]
set_location_assignment PIN_H14 -to LCD_DATA[2]
set_location_assignment PIN_C17 -to LCD_DATA[1]
set_location_assignment PIN_D15 -to LCD_DATA[0]
set_location_assignment PIN_B20 -to LCD_RS
set_location_assignment PIN_C13 -to LCD_RST_N
set_location_assignment PIN_C19 -to LCD_CS_N
set_location_assignment PIN_A20 -to LCD_WR_N
set_location_assignment PIN_D13 -to LCD_RD_N

set_location_assignment PIN_E22 -to TOUCH_INT
set_location_assignment PIN_F22 -to TOUCH_RST_N
set_location_assignment PIN_F21 -to TOUCH_SCL
set_location_assignment PIN_D21 -to TOUCH_SDA
