// Copyright (C) 1991-2016 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus Prime License Agreement,
// the Altera MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Altera and sold by Altera or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus Prime Version 16.0 (Build Build 211 04/27/2016)
// Created on Sun Sep 30 11:02:32 2018

meas_freq meas_freq_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.square(square_sig) ,	// input  square_sig
	.CNTCLK(CNTCLK_sig) ,	// output [27:0] CNTCLK_sig
	.CNTSQU(CNTSQU_sig) 	// output [27:0] CNTSQU_sig
);

defparam meas_freq_inst.GATE_TIME = 'b0101111101011110000011111111;
