// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Intel and sold by Intel or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus Prime Version 17.0 (Build Build 595 04/25/2017)
// Created on Sat Apr 13 14:58:21 2019

nco nco_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.clken(clken_sig) ,	// input  clken_sig
	.phi_inc_i(phi_inc_i_sig) ,	// input [31:0] phi_inc_i_sig
	.freq_mod_i(freq_mod_i_sig) ,	// input [31:0] freq_mod_i_sig
	.phase_mod_i(phase_mod_i_sig) ,	// input [15:0] phase_mod_i_sig
	.fsin_o(fsin_o_sig) ,	// output [15:0] fsin_o_sig
	.out_valid(out_valid_sig) ,	// output  out_valid_sig
	.reset_n(reset_n_sig) 	// input  reset_n_sig
);

